# texts.py
RUSSIAN_TEXTS = {
    "app_title": "Система управления версиями дашбордов",
    "upload_header": "Загрузка новой версии",
    "dashboard_name": "Название дашборда",
    "screenshot": "Скриншот дашборда",
    "version_description": "Описание версии",
    "version_description_placeholder": "Что изменилось в этой версии?",
    "upload_button": "Загрузить",
    "upload_success": "Загружена версия",
    "changes_from_previous": "Отличий от предыдущей версии",
    "upload_first": "Загружена первая версия",
    "history_tab": "История версий",
    "compare_tab": "Сравнение дашбордов",
    "no_dashboards": "Нет загруженных дашбордов. Загрузите первый скриншот в боковой панели.",
    "select_dashboard": "Выберите дашборд",
    "version": "Версия",
    "description_label": "Описание",
    "no_description": "Нет описания",
    "changes_from_previous_label": "Изменения относительно предыдущей версии",
    "similarity": "Схожесть",
    "changed": "Изменено",
    "verdict": "Вердикт",
    "compare_header": "Сравнение двух версий",
    "first_dashboard": "Первый дашборд",
    "second_dashboard": "Второй дашборд",
    "compare_button": "Сравнить",
    "analysis": "Анализ",
    "visual_comparison": "Визуальное сравнение",
    "difference_overlay": "Наложение различий (красным отмечены изменения)",
    "detailed_heatmap": "Детальная тепловая карта",
    "almost_identical": "Практически идентичны",
    "minor_changes": "Незначительные изменения",
    "notable_changes": "Заметные изменения",
    "significant_differences": "Сильно отличаются",
    "minimal_differences": "Минимальные различия, возможно артефакты сжатия",
    "small_local_changes": "Небольшие локальные изменения",
    "moderate_changes": "Умеренные изменения",
    "major_layout_changes": "Существенные изменения макета",
    "changes_in_area": "Изменения обнаружены в области",
    "left_area": "левой",
    "center_area": "центральной",
    "right_area": "правой",
    "visually_close": "Дашборды визуально очень близки",
    "completely_different": "Дашборды выглядят как совершенно разные"
}